export default {
    books: [],
    rates: [],
    selectedBooks: [],
    categories: [],
    subcategories: [],
    booksOfCategory: [],
    valueOfCategory:[],
    booksOfSubcategory:[],
    valueOfSubcategory: [],
    error: [],
    valueOfBook: [],
    token: '',
    loginStatus: false,
  }